version: '3.8'

services:
  geoserver:
    image: kartoza/geoserver:2.26.0
    container_name: geoserver
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    # ports:
    #   - "8080:8080" 
    volumes:
      - /home/tungba103/geoserver/data_dir:/opt/geoserver/data_dir
    # depends_on:
    #   - db
    network_mode: "host"

#   db:
#     image: postgis/postgis
#     container_name: postgis
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=123123
#       - POSTGRES_DB=postgis
#     volumes:
#       - postgis_data:/var/lib/postgresql/data
#     network_mode: "host"

# volumes:
#   postgis_data:
